baseurl = "/"
languageCode = "en-us"
title = "Ethan DENG's Personal Page"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:year-:month-:day/:slug/"
    note = "/note-:year-:month-:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Resource"
    url = "/resource/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 5

[params]
    description = "Ethan DENG's Personal Website"
    footer = "&copy; [EthanDENG](https://ddswhu.me/) 2018 -- 2020 Theme [XMin](https://themes.gohugo.io/hugo-xmin/) Powered by Hugo and Netlify"
